Исключение происходит в специальном потоке EDT – Event Dispathing Thread. Этот
поток совершает диспетчеризацию всех событий, происходящих во фреймворке
Swing и является генератором других потоков

SwingUtilites.invokeLater(new Runnable() {
  @Ovveride
  public void run() {
    new Exception();
  }
});

Если внимательно изучить текст исключения
внизу экрана на рисунке 10, очевидно, что исключение возникло в потоке с
названием AWT-EventQueue-0. Наличие у потока номера говорит о том, что таких
очередей событий у приложения может быть много, и в каких-то из них могут
возникать исключения. Исключение происходит в потоке. Обработчик исключений
тоже содержится в потоке и называется Thread.UncaughtExceptionHandler и
является интерфейсом

Интерфейс содержит один метод – непойманное
исключение, который принимает на вход поток, в котором произошло исключение и
объект исключения, которое произошло

implement Thread.UncaughtExceptionHandler
@Override
public void uncaughtException(Thread t, Throwable e) {
  код при возникновении исключения
  JOptionPane.showMessageDialog(null, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
}